orbs:
  node: circleci/node@4.0.0

version: 2.1

jobs:
  build-plugin:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install

workflows:
    build-and-test:
      jobs:
        - build-plugin