orbs:
  node: circleci/node@4.0.0

version: 2.1

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm i -g parcel-bundler
      - run: npm run build

workflows:
    build-and-test:
      jobs:
        - build-and-test